body:
  - type: textBlock
    attributes:
      name: description
      description: "Open ChatGPT with a populated prompt from query"

  - type: dropdown
    attributes:
      name: default_model
      label: "Default Model for OpenAI Chat:"
      defaultValue: "text-davinci-002-render-sha"  # GPT 3.5
      description: "Set the default model to use in OpenAI Chat (e.g., gpt-3.5-turbo, gpt-4, etc.)"
      options:
      - "text-davinci-002-render-sha"
      - "gpt-4"